// Generated by CoffeeScript 1.6.2
var OrganisationSchema, Schema, mongoose;

mongoose = require("mongoose");

Schema = mongoose.Schema;

OrganisationSchema = Schema({
  _admin: {
    type: Schema.Types.ObjectId,
    ref: 'Admin',
    required: true
  },
  name: {
    type: String,
    required: true
  },
  thumb: {
    type: String
  },
  description: {
    type: String
  },
  conferences: [
    {
      type: Schema.Types.ObjectId,
      ref: 'Conference',
      index: {
        unique: true
      }
    }
  ]
});

module.exports = mongoose.model('Organisation', OrganisationSchema, 'organisations');
