// Generated by CoffeeScript 1.4.0
var Admin, Conference, Config, Organisation, Schema, Slide, confDB, dsn, getOrgaList, getOrgaListfromAdmin, mongoose, readConference, readSlideList, readSlideListForSlider, readSlideToSend, setSent,
  _this = this;

mongoose = require('mongoose');

Schema = mongoose.Schema;

Admin = require('./Models/Admin.js');

Slide = require('./Models/Slide.js');

Organisation = require("./Models/Organisation.js");

Conference = require("./Models/Conference.js");

Config = require("./config");

dsn = Config.dsn;

mongoose.connect(dsn);

confDB = mongoose.connection;

confDB.on('error', console.error.bind(console, 'connection error com:'));

module.exports.getOrgaListfromAdmin = getOrgaListfromAdmin = function(AdminEmail, callback) {
  var organisation;
  organisation = null;
  return Admin.findOne({
    email: AdminEmail
  }, function(err, admin) {
    console.log(admin);
    if (err) {
      console.log(err);
    }
  }).populate('organisations').exec(function(err, admin) {
    var organisations;
    organisations = admin.organisations;
    return callback(organisations);
  });
};

module.exports.getOrgaList = getOrgaList = function(callback) {
  var organisation;
  organisation = null;
  return Organisation.find(function(err, organisations) {
    if (err) {
      console.log("find erreur man");
    }
    if (organisations.length > 0) {
      organisation = organisations;
      return callback(organisation);
    }
  });
};

module.exports.readConference = readConference = function(OrgId, callback) {
  var Confs,
    _this = this;
  Confs = null;
  return Organisation.findOne({
    _id: OrgId
  }, function(err, organisation) {
    if (err) {
      return console.log("error while trying to find the organisations of this admin");
    }
  }).populate('conferences').exec(function(err, organisation) {
    Confs = organisation.conferences;
    return callback(Confs);
  });
};

module.exports.readSlideList = readSlideList = function(ConfId, callback) {
  var slides,
    _this = this;
  slides = [];
  return Conference.findOne({
    _id: ConfId
  }, function(err, conference) {
    if (err) {
      return console.log("error while trying to find the organisations of this admin");
    }
  }).populate('slides').exec(function(err, conferences) {
    var slide, _i, _len, _ref;
    _ref = conferences.slides;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      slide = _ref[_i];
      if (slide.Sent) {
        slides.push(slide);
      }
    }
    return callback(slides);
  });
};

module.exports.readSlideListForSlider = readSlideListForSlider = function(ConfId, callback) {
  var slides,
    _this = this;
  slides = null;
  return Conference.findOne({
    _id: ConfId
  }, function(err, conference) {
    if (err) {
      return console.log("error while trying to find the organisations of this admin");
    }
  }).populate('slides').exec(function(err, conference) {
    return callback(conference.slides);
  });
};

module.exports.readSlideToSend = readSlideToSend = function(slideId, callback) {
  var _this = this;
  return Slide.findOne({
    _id: slideId
  }, function(err, slide) {
    if (err) {
      console.log("voici l'erreur", err);
    }
    return callback(slide);
  });
};

module.exports.setSent = setSent = function(sent, id) {
  return Slide.update({
    _id: id
  }, {
    Sent: sent
  }, {
    multi: true
  }, function(err, numberAffected, raw) {});
};
