// Generated by CoffeeScript 1.6.2
var Admin, Schema, confDB, dsn, mongoose;

mongoose = require('mongoose');

Schema = mongoose.Schema;

Admin = require('./Models/Admin.js');

dsn = "mongodb://localhost/DirectPlus";

mongoose.connect(dsn);

confDB = mongoose.connection;

confDB.on('error', console.error.bind(console, 'connection error:'));

console.log("trying to open database");

confDB.once('open', function() {
  var Seba;

  console.log("open database");
  Seba = new Admin({
    firstname: 'Sebastien',
    lastname: 'Barbieri',
    email: 'seba@rtbf.be'
  });
  return Seba.save(function(err, fabriceData) {
    if (err) {
      console.log("saving error man");
      console.log(err);
    } else {
      console.log('Seba as admin added');
    }
    return confDB.close();
  });
});

/*
//@ sourceMappingURL=dbSetup.map
*/
