// Generated by CoffeeScript 1.6.2
var Admin, Schema, confDB, dsn, mongoose, operationDone, operationsRunning;

mongoose = require('mongoose');

Schema = mongoose.Schema;

Admin = require('./Models/Admin.js');

dsn = "mongodb://localhost/DirectPlus";

mongoose.connect(dsn);

confDB = mongoose.connection;

confDB.on('error', console.error.bind(console, 'connection error:'));

operationsRunning = 0;

operationDone = function() {
  operationsRunning--;
  if (operationsRunning <= 0) {
    confDB.close();
    return console.log("db setup finished");
  }
};

confDB.once('open', function() {
  var Exception, Seba;

  Seba = new Admin({
    firstname: 'Sebastien',
    lastname: 'Barbieri',
    email: 'seba@rtbf.be'
  });
  operationsRunning++;
  try {
    return Seba.save(function(err, fabriceData) {
      if (err) {
        console.log("error occured");
        if (err.code === 11000) {
          console.log("admin already added");
        }
      } else {
        console.log('Seba as admin added');
      }
      return operationDone();
    });
  } catch (_error) {
    Exception = _error;
  }
});

/*
//@ sourceMappingURL=dbSetup.map
*/
