// Generated by CoffeeScript 1.4.0
var Admin, Conference, Organisation, Schema, Slide, confDB, dsn, mongoose;

mongoose = require('mongoose');

Schema = mongoose.Schema;

Admin = require('./Models/Admin.js');

Slide = require('./Models/Slide.js');

Organisation = require("./Models/Organisation.js");

Conference = require("./Models/Conference.js");

dsn = "mongodb://localhost/DirectPlus";

mongoose.connect(dsn);

confDB = mongoose.connection;

confDB.on('error', console.error.bind(console, 'connection error:'));

confDB.once('open', function() {
  var _this = this;
  return Conference.find(function(err, confs) {
    var conf, _i, _len, _results;
    if (err) {
      console.log("erreur: ", err);
    }
    _results = [];
    for (_i = 0, _len = confs.length; _i < _len; _i++) {
      conf = confs[_i];
      _results.push(conf.remove());
    }
    return _results;
  });
});
